//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiClinicGAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int idAppointment { get; set; }
        public int fk_idPatient { get; set; }
        public int fk_idAppointmentType { get; set; }
        public int fk_idDoctor { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public bool isActive { get; set; }
    
        public virtual AppointmentsTypes AppointmentsTypes { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
